name: "r2s-openwrt-nightly"

on:
  schedule:
    - cron: 0 20 * * * # 定时任务触发
  push:
    branches:
      - main # 修改主分支时触发ci流程

jobs:
  r2s-openwrt-nightly:
    runs-on: ubuntu-latest
    name: r2s-openwrt-nightly
    steps:
      - name: Check out # 检出配置
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup # 清理磁盘空间
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Init # 初始化构建环境
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
          git clone https://github.com/coolsnowwolf/lede

      - name: Modify Feeds Config # 定制化Feeds配置
        working-directory: $GITHUB_WORKSPACE/lede/
        run: |
          # 移除HelloWorld行的注释
          sed -i 's/^#\(.*helloworld\)/\1/' ./feeds.conf.default
          # 添加新的feeds源
          sed -i '$a src-git jerryk https://github.com/jerrykuku/openwrt-package' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Modify Static IP Config # 定制化路由器IP地址,替换192.168.1.1后面的部分
        working-directory: $GITHUB_WORKSPACE/lede/
        run: |
          # 修改路由器IP地址
          sed -i 's/192.168.1.1/192.168.10.1/g' ./package/base-files/files/bin/config_generate

      - name: Generate configuration file # 生成配置文件
        working-directory: $GITHUB_WORKSPACE/lede/
        run: |
          rm -f ./.config*
          mv $GITHUB_WORKSPACE/openwrt-nightly/config.txt ./.config
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download # 下载相关依赖文件
        working-directory: $GITHUB_WORKSPACE/lede/
        run: |
          make download -j8

      - name: Compile firmware # 编译OpenWRT
        working-directory: $GITHUB_WORKSPACE/lede/
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Prepare artifact # 收集需要上传的文件
        working-directory: $GITHUB_WORKSPACE/lede/
        run: |
          mkdir -p ./upload
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./upload/

      - name: Upload release # 上传编译产物
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: $GITHUB_WORKSPACE/lede/upload/
