name: r2s-openwrt-nightly

on:
  schedule:
    - cron: 0 20 * * * # 定时任务触发
  push:
    branches:
      - main # 修改主分支时触发ci流程

jobs:
  r2s-openwrt-nightly:
    runs-on: ubuntu-latest
    name: r2s-openwrt-nightly

    steps:
      - name: Checkout # 检出配置
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout code # 检出代码
        run: |
          pwd
          git clone https://github.com/coolsnowwolf/lede  