name: r2s-openwrt-test

on:
  push:
    branches:
      - dev # 修改dev分支时触发ci流程

jobs:
  r2s-openwrt-test:
    runs-on: ubuntu-latest
    name: r2s-openwrt-test

    steps:
      - name: Checkout # 检出配置
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Checkout code # 检出代码
        run: |
          cd ..
          git clone https://github.com/coolsnowwolf/lede

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update 
          sudo -E apt-get -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Update feeds # 更新feeds
        run: |
          cd ../lede
          # 添加新的feeds源
          sed -i '$a src-git jerryk https://github.com/jerrykuku/openwrt-package' ./feeds.conf.default
          sed -i '$a src-git helloworld https://github.com/fw876/helloworld' ./feeds.conf.default
          sed -i '$a src-git nas https://github.com/linkease/nas-packages.git;master' ./feeds.conf.default
          sed -i '$a src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main' ./feeds.conf.default
          # sed -i '$a src-git passwall https://github.com/xiaorouji/openwrt-passwall' ./feeds.conf.default
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Modify Static IP Config # 定制化路由器IP地址,替换192.168.1.1后面的部分
        run: |
          cd ../lede
          # 修改路由器IP地址
          sed -i 's/192.168.1.1/192.168.10.1/g' ./package/base-files/files/bin/config_generate

      - name: Generate configuration file # 生成编译配置
        run: |
          cd ../lede
          rm -f ./.config*
          mv $GITHUB_WORKSPACE/config.txt ./.config
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download # 预下载数据
        run: |
          cd ../lede
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware # 编译固件
        run: |
          cd ../lede
          make -j$(nproc) || make -j1 V=s

      - name: Prepare artifact # 准备上传文件
        run: |
          cd ../lede
          mkdir -p $GITHUB_WORKSPACE/artifact/firmware
          mkdir -p $GITHUB_WORKSPACE/artifact/package
          mkdir -p $GITHUB_WORKSPACE/artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) $GITHUB_WORKSPACE/artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") $GITHUB_WORKSPACE/artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") $GITHUB_WORKSPACE/artifact/buildinfo/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./artifact/firmware/
